sudo: required
env:
- GHCVER=8.0.2
- GHCVER=8.2.2
- GHCVER=8.4.1
- GHCVER=head

script:
- export HLINT_ARGUMENTS=src demo
- curl -sL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh
- qed qed-demo.hs
